---
- hosts: bench_machine
  become: true
  tasks:
    - name: start network io benchmarking container
      docker_container:
        name: network_io_benchmark
        image: automaat/network_io_benchmark
        ports:
          - "8080:8080"